/**
 * Configuración global de la aplicación
 */
export const CONFIG = {
    // Posición inicial del eje X
    IZQUIERDA_X: 300,
    
    // Escala vertical (píxeles por metro)
    PIXELES_POR_METRO: 100,
    
    // Escala horizontal
    ANCHO_ESCALA_HORIZONTAL: 200,
    DESPLAZAMIENTO_ESCALA_HORIZONTAL: 0,
    
    // Separación mínima entre etiquetas de escala
    SEPARACION_MINIMA_ETIQUETAS: 100,
    
    // Mostrar guías verticales
    MOSTRAR_GUIAS_VERTICALES: false,
    
    // Invertir escala (profundidad desde superficie)
    INVERTIR_ESCALA: false,
    
    // Márgenes del canvas
    MARGEN_SUPERIOR: 100,
    MARGEN_INFERIOR: 200,
    
    // Ancho mínimo del canvas
    ANCHO_MINIMO: 800,

    
   
    
    // Tamaño por defecto de nuevos estratos
    ESTRATO_ALTO_DEFAULT: 150,
    ESTRATO_ANCHO_DEFAULT: 300,
    ESTRATO_COLOR_DEFAULT: "#cccccc",
    ESTRATO_TRAMA_DEFAULT: "solido",
    ESTRATO_TAMANO_TRAMA_DEFAULT: 100,
    ESTRATO_TIPO_BORDE_DEFAULT: "recto"
};

/**
 * Traducciones de tramas
 */
export const TRADUCCIONES_TRAMA = {
    "solido": "Color sólido",
    "conglomerado_op1": "601 Grava o conglomerado opción 1",
    "conglomerado_op2": "602 Conglomerado o grava opción 2",
    "conglomerado_cruzado": "603 Grava o conglomerado con estratificación cruzada",
    "brecha_op1": "605 Brecha 1ra opción",
    "brecha_op2": "606 Brecha 2da opción",
    "arenisca_maciza": "607 Arenisca o arena maciza",
    "arenisca_estratificada": "608 Arenisca o arena estratificada",
    "arenisca_cruzada_op1": "609 Arenisca o arena con estratificación cruzada 1ra opción",
    "arenisca_cruzada_op2": "610 Arenisca o arena con estratificación cruzada 2da opción",
    "arenisca_ondulada": "611 Arenisca o arena con estratificación ondulada",
    "arenisca_arcillosa": "612 Arenisca arcillosa o argilizada",
    "arenisca_calcare": "613 Arenisca calcárea",
    "arenisca_dolomitica": "614 Arenisca dolomítica",
    "limolita_arcillosa": "616 Limo, limolita o lutita arcillosa",
    "limolita_calcare": "617 Limolita calcárea",
    "limolita_dolomitica": "618 Limolita dolomítica",
    "lutita_arenosa": "619 Lutita arenosa o limosa",
    "lutita": "620 Arcilla o lutita",
    "lutita_chert": "621 Lutita chert o chert pizarroso",
    "lutita_dolomitica": "622 Lutita dolomítica",
    "lutita_calcare": "623 Lutita calcárea o mármol",
    "lutita_carbonosa": "624 Lutita carbonosa",
    "lutita_petrolifera": "625 Lutita petrolífera",
    "creta": "626 Creta",
    "caliza": "627 Caliza",
    "caliza_clastica": "628 Caliza clástica",
    "caliza_fosilifera": "629 Caliza fosilífera clástica",
    "caliza_nodular": "630 Caliza nodular o con estratificación irregular",
    "caliza_madrigueras": "631 Caliza, rellenos irregulares (madrigueras) de dolomita sacaroidal",
    "caliza_cruzada": "632 Caliza con estratificación cruzada",
    "caliza_chert_cruzada": "633 Caliza chert con estratificación cruzada",
    "caliza_arenosa_chert": "634 Caliza arenosa y con chert, clástica con estratificación cruzada",
    "caliza_oolitica": "635 Caliza oolítica",
    "caliza_arenosa": "636 Caliza arenosa",
    "caliza_limosa": "637 Caliza limosa",
    "caliza_lutitica": "638 Caliza lutítica o arcillosa",
    "caliza_chert_op1": "639 Caliza con chert 1ra opción",
    "caliza_chert_op2": "640 Caliza con chert 2da opción",
    "caliza_dolomitica": "641 Caliza dolomítica, dolomita calcárea",
    "dolomita": "642 Dolomita o dolomía",
    "dolomita_cruzada": "643 Dolomita o dolomía con estratificación cruzada",
    "dolomita_oolitica": "644 Dolomita o dolomía oolítica",
    "dolomita_arenosa": "645 Dolomita o dolomía arenosa",
    "dolomita_limosa": "646 Dolomita o dolomía limosa",
    "dolomita_lutitica": "647 Dolomita o dolomía arcillosa o lutítica",
    "dolomita_chert": "648 Dolomita o dolomía con chert",
    "chert_op1": "649 Chert estratificado 1ra opción",
    "chert_op2": "650 Chert estratificado 2da opción",
    "chert_fosilifero": "651 Chert estratificado fosilífero",
    "roca_fosilifera": "652 Roca fosilífera",
    "roca_diatomitica": "653 Roca diatomítica o con diatomeas",
    "subgrauvaca": "654 Subgrauvaca",
    "subgrauvaca_cruzada": "655 Subgrauvaca con estratificación cruzada",
    "subgrauvaca_ondulada": "656 Subgrauvaca con estratificación ondulada",
    "turba": "657 Turba",
    "carbon": "658 Carbón",
    "carbon_impuro": "659 Carbón con huesos o impuro",
    "paleosuelo": "660 Paleosuelo, arcilla basal, underclay",
    "flintclay": "661 Flintclay o pedernal",
    "bentonita": "662 Bentonita",
    "glauconita": "663 Glauconita",
    "limonita": "664 Limonita",
    "siderita": "665 Siderita",
    "fosforita": "666 Roca fosfática nodular, fósforita",
    "yeso": "667 Yeso",
    "sal": "668 Sal",
    "arenisca_limolita": "669 Arenisca y limolita interestratificada",
    "arenisca_lutita": "670 Arenisca y lutita interestratificada",
    "arenisca_lutita_ondulada": "671 Arenisca y lutita interestratificada con estratificación ondulada",
    "lutita_caliza_limosa": "672 Lutita y caliza limosa interestratificada",
    "lutita_caliza_op1": "673 Lutita y caliza interestratificada 1ra opción",
    "lutita_caliza_op2": "674 Lutita y caliza interestratificada 2da opción",
    "lutita_caliza_calcare": "675 Lutita calcárea y caliza interestratificada",
    "caliza_limosa_lutita_op1": "676 Caliza limosa y lutita interestratificada 1ra opción",
    "caliza_lutita_op1": "677 Caliza y lutita interestratificada 1ra opción",
    "caliza_lutita_op2": "678 Caliza y lutita interestratificada 2da opción",
    "caliza_lutita_op3": "679 Caliza y lutita interestratificada 3ra opción",
    "caliza_lutita_calcare": "680 Caliza y lutita calcárea interestratificada",
    "till_op1": "681 Till o diamicto 1ra opción",
    "till_op2": "682 Till o diamicto 2da opción",
    "till_op3": "683 Till o diamicto 3ra opción",
    "loess_op1": "684 Loess 1ra opción",
    "loess_op2": "685 Loess 2da opción",
    "loess_op3": "686 Loess 3ra opción",
    "metamorfismo": "701 Metamorfismo",
    "cuarcita": "702 Cuarcita",
    "pizarra": "703 Pizarra",
    "granito_esquistoso": "704 Granito esquistoso o gneísico",
    "esquisto": "705 Esquisto",
    "esquisto_contorsionado": "706 Esquisto contorsionado",
    "esquisto_gneis": "707 Esquisto y gneis",
    "gneis": "708 Gneis",
    "gneis_contorsionado": "709 Gneis contorsionado",
    "esteatita": "710 Esteatita, talco o serpentinita",
    "roca_tufitica": "711 Roca tufítica",
    "toba_cristalina": "712 Toba cristalina",
    "toba_desvitrificada": "713 Toba desvitrificada",
    "brecha_volcanica_toba": "714 Brecha volcánica y toba",
    "brecha_volcanica": "715 Brecha volcánica o aglomerado",
    "roca_zeolitica": "716 Roca zeolítica",
    "flujos_basalticos": "717 Flujos basálticos",
    "granito_op1": "718 Granito 1ra opción",
    "granito_op2": "719 Granito 2da opción",
    "roca_ignea_bandeada": "720 Roca ígnea bandeada",
    "roca_ignea_op1": "721 Roca ígnea 1ra opción",
    "roca_ignea_op2": "722 Roca ígnea 2da opción",
    "roca_ignea_op3": "723 Roca ígnea 3ra opción",
    "roca_ignea_op4": "724 Roca ígnea 4ta",
    "roca_ignea_op5": "725 Roca ígnea 5ta",
    "roca_ignea_op6": "726 Roca ígnea 6ta",
    "roca_ignea_op7": "727 Roca ígnea 7ma",
    "roca_ignea_op8": "728 Roca ígnea 8va",
    "roca_porfirica_op1": "729 Roca porfírica 1ra opción",
    "roca_porfirica_op2": "730 Roca porfírica 2da opción",
    "vitrofiro": "731 Vitrófiro",
    "cuarzo": "732 Cuarzo",
    "mineralizacion": "733 Mineralización",
    "SNGM 001 Grava o conglomerado imbricado clastosoportado": "SNGM 001 Grava o conglomerado imbricado clastosoportado"
    
};

/**
 * Traducciones de símbolos (fósiles)
 */
export const TRADUCCIONES_SIMBOLOS = {
    "10.2.1 Macrofosiles": "Macrofósiles",
    "10.2.2 Invertebrados": "Invertebrados",
    "10.2.3 Anélidos": "Anélidos",
    "10.2.4 Artrópodos": "Artrópodos",
    "10.2.5 Aracnidos": "Arácnidos",
    "10.2.6 Crustáceos": "Crustáceos",
    "10.2.7 Insectos": "Insectos",
    "10.2.8 Trilobites": "Trilobites",
    "10.2.9 Braquiopodos": "Braquiópodos",
    "10.2.10 Briozoos": "Briozoos",
    "10.2.11 Cnidarios": "Cnidarios",
    "10.2.12 Corales": "Corales",
    "10.2.13 Estromatoporoideos": "Estromatoporoideos",
    "10.2.14 Equinodermos": "Equinodermos",
    "10.2.15 Crinoideos": "Crinoideos",
    "10.2.16 Equinoideos": "Equinoideos",
    "10.2.17 Graptolitos": "Graptolitos",
    "10.2.18 moluscos": "Moluscos",
    "10.2.19 Cefalópodos": "Cefalópodos",
    "10.2.20 Amonoideos": "Amonoideos",
    "10.2.21 Belemnoideos": "Belemnoideos",
    "10.2.22 Nautiloideos": "Nautiloideos",
    "10.2.23 Gastrópodos": "Gastrópodos",
    "10.2.24 Pelecípodos": "Pelecípodos",
    "10.2.25 Esponjas": "Esponjas",
    "10.2.26 Vertebrados": "Vertebrados",
    "10.2.27 Anfibios": "Anfibios",
    "10.2.28 Peces": "Peces",
    "10.2.29 Mamíferos": "Mamíferos",
    "10.2.30 Reptiles": "Reptiles",
    "10.2.31 Plantas": "Plantas",
    "10.2.32 Hojas": "Hojas",
    "10.2.33 Raíces": "Raíces",
    "10.2.34 Madera": "Madera",
    "10.2.35 Algas": "Algas",
    "10.2.36 Coníferas": "Coníferas",
    "10.2.37 Helechos": "Helechos",
    "10.2.38 Plantas o árboles con flores": "Plantas o árboles con flores",
    "10.2.39 Estromatolitos": "Estromatolitos",
    "10.2.40 Fungi": "Fungi",
    "10.2.41 Trazas fósiles": "Trazas fósiles",
    "10.2.42 Madrigueras": "Madrigueras",
    "10.2.43 Coprolitos": "Coprolitos",
    "10.2.44 Huellas": "Huellas",
    "10.2.45 Microfósiles": "Microfósiles",
    "10.2.46 Conodontos": "Conodontos",
    "10.2.47 Diatomeas": "Diatomeas",
    "10.2.48 Foraminíferos": "Foraminíferos",
    "10.2.49 Grandes foraminíferos o fusulínidos": "Grandes foraminíferos o fusulínidos",
    "10.2.50 Foraminíferos bentónicos, pequeños": "Foraminíferos bentónicos, pequeños",
    "10.2.51 Foraminíferos planctónicos, pequeños": "Foraminíferos planctónicos, pequeños",
    "10.2.52 Nanofósiles": "Nanofósiles",
    "10.2.53 Ostrácodos": "Ostrácodos",
    "10.2.54 Palinomorfos": "Palinomorfos",
    "10.2.55 Acritarcos": "Acritarcos",
    "10.2.56 Quitinozoos": "Quitinozoos",
    "10.2.57 Dinoflagelados": "Dinoflagelados",
    "10.2.58 Polen o esporas": "Polen o esporas",
    "10.2.59 Radiolarios": "Radiolarios",
    "10.2.60 Silicoflagelados": "Silicoflagelados",
    "10.2.61 Espículas": "Espículas",
    "concreciones": "Concreciones",
    "meteorizacion_esferoidal": "Meteorización esferoidal",
    "raices": "Raíces",
    "SNGM Algas calcáreas": "Algas calcáreas",
    "SNGM Bioturbación": "Bioturbación",
    "SNGM Diatomeas": "Diatomeas",
    "SNGM Fauna fósil indiferenciada": "Fauna fósil indiferenciada",
    "SNGM Flora fósil": "Flora fósil",
    "SNGM Foraminíferos": "Foraminíferos",
    "SNGM Invertebrados marinos": "Invertebrados marinos",
    "SNGM Mamíferos marinos": "Mamíferos marinos",
    "SNGM Microfauna sin especificar": "Microfauna sin especificar",
    "SNGM Peces, esqueletos y escamas": "Peces, esqueletos y escamas",
    "SNGM Polen y o esporas": "Polen o esporas",
    "SNGM Radiolarios": "Radiolarios",
    "SNGM Raiz en posición de vida": "Raíz en posición de vida",
    "SNGM Rastros y pisadas 1": "Rastros y pisadas (1)",
    "SNGM Rastros y pisadas 2": "Rastros y pisadas (2)",
    "SNGM Restos de tronco": "Restos de tronco",
    "SNGM Trazas fósiles 2": "Trazas fósiles (2)",
    "SNGM Trazas fósiles 3": "Trazas fósiles (3)",
    "SNGM Trazas fósiles": "Trazas fósiles",
    "SNGM Tronco en posición de vida": "Tronco en posición de vida",
    "SNGM Vertebrados": "Vertebrados"
};

/**
 * Lista de tramas para registrar
 */
export const LISTA_TRAMAS = [
    "conglomerado_op1", "conglomerado_op2", "conglomerado_cruzado",
    "brecha_op1", "brecha_op2", "arenisca_maciza", "arenisca_estratificada",
    "arenisca_cruzada_op1", "arenisca_cruzada_op2", "arenisca_ondulada",
    "arenisca_arcillosa", "arenisca_calcare", "arenisca_dolomitica",
    "limolita_arcillosa", "limolita_calcare", "limolita_dolomitica",
    "lutita_arenosa", "lutita", "lutita_chert", "lutita_dolomitica",
    "lutita_calcare", "lutita_carbonosa", "lutita_petrolifera",
    "creta", "caliza", "caliza_clastica", "caliza_fosilifera",
    "caliza_nodular", "caliza_madrigueras", "caliza_cruzada",
    "caliza_chert_cruzada", "caliza_arenosa_chert", "caliza_oolitica",
    "caliza_arenosa", "caliza_limosa", "caliza_lutitica",
    "caliza_chert_op1", "caliza_chert_op2", "caliza_dolomitica",
    "dolomita", "dolomita_cruzada", "dolomita_oolitica",
    "dolomita_arenosa", "dolomita_limosa", "dolomita_lutitica",
    "dolomita_chert", "chert_op1", "chert_op2", "chert_fosilifero",
    "roca_fosilifera", "roca_diatomitica", "subgrauvaca",
    "subgrauvaca_cruzada", "subgrauvaca_ondulada", "turba",
    "carbon", "carbon_impuro", "paleosuelo", "flintclay",
    "bentonita", "glauconita", "limonita", "siderita",
    "fosforita", "yeso", "sal", "arenisca_limolita",
    "arenisca_lutita", "arenisca_lutita_ondulada",
    "lutita_caliza_limosa", "lutita_caliza_op1", "lutita_caliza_op2",
    "lutita_caliza_calcare", "caliza_limosa_lutita_op1",
    "caliza_lutita_op1", "caliza_lutita_op2", "caliza_lutita_op3",
    "caliza_lutita_calcare", "till_op1", "till_op2", "till_op3",
    "loess_op1", "loess_op2", "loess_op3", "metamorfismo",
    "cuarcita", "pizarra", "granito_esquistoso", "esquisto",
    "esquisto_contorsionado", "esquisto_gneis", "gneis",
    "gneis_contorsionado", "esteatita", "roca_tufitica",
    "toba_cristalina", "toba_desvitrificada", "brecha_volcanica_toba",
    "brecha_volcanica", "roca_zeolitica", "flujos_basalticos",
    "granito_op1", "granito_op2", "roca_ignea_bandeada",
    "roca_ignea_op1", "roca_ignea_op2", "roca_ignea_op3",
    "roca_ignea_op4", "roca_ignea_op5", "roca_ignea_op6",
    "roca_ignea_op7", "roca_ignea_op8", "roca_porfirica_op1",
    "roca_porfirica_op2", "vitrofiro", "cuarzo", "mineralizacion",
    "SNGM 001 Grava o conglomerado imbricado clastosoportado"
];

/**
 * Lista de símbolos para registrar
 */
export const LISTA_SIMBOLOS = [
    "10.2.1 Macrofosiles", "10.2.2 Invertebrados", "10.2.3 Anélidos",
    "10.2.4 Artrópodos", "10.2.5 Aracnidos", "10.2.6 Crustáceos",
    "10.2.7 Insectos", "10.2.8 Trilobites", "10.2.9 Braquiopodos",
    "10.2.10 Briozoos", "10.2.11 Cnidarios", "10.2.12 Corales",
    "10.2.13 Estromatoporoideos", "10.2.14 Equinodermos",
    "10.2.15 Crinoideos", "10.2.16 Equinoideos", "10.2.17 Graptolitos",
    "10.2.18 moluscos", "10.2.19 Cefalópodos", "10.2.20 Amonoideos",
    "10.2.21 Belemnoideos", "10.2.22 Nautiloideos", "10.2.23 Gastrópodos",
    "10.2.24 Pelecípodos", "10.2.25 Esponjas", "10.2.26 Vertebrados",
    "10.2.27 Anfibios", "10.2.28 Peces", "10.2.29 Mamíferos",
    "10.2.30 Reptiles", "10.2.31 Plantas", "10.2.32 Hojas",
    "10.2.33 Raíces", "10.2.34 Madera", "10.2.35 Algas",
    "10.2.36 Coníferas", "10.2.37 Helechos",
    "10.2.38 Plantas o árboles con flores", "10.2.39 Estromatolitos",
    "10.2.40 Fungi", "10.2.41 Trazas fósiles", "10.2.42 Madrigueras",
    "10.2.43 Coprolitos", "10.2.44 Huellas", "10.2.45 Microfósiles",
    "10.2.46 Conodontos", "10.2.47 Diatomeas", "10.2.48 Foraminíferos",
    "10.2.49 Grandes foraminíferos o fusulínidos",
    "10.2.50 Foraminíferos bentónicos, pequeños",
    "10.2.51 Foraminíferos planctónicos, pequeños",
    "10.2.52 Nanofósiles", "10.2.53 Ostrácodos", "10.2.54 Palinomorfos",
    "10.2.55 Acritarcos", "10.2.56 Quitinozoos", "10.2.57 Dinoflagelados",
    "10.2.58 Polen o esporas", "10.2.59 Radiolarios",
    "10.2.60 Silicoflagelados", "10.2.61 Espículas",
    "concreciones", "meteorizacion_esferoidal", "raices",
    "SNGM Algas calcáreas", "SNGM Bioturbación", "SNGM Diatomeas",
    "SNGM Fauna fósil indiferenciada", "SNGM Flora fósil",
    "SNGM Foraminíferos", "SNGM Invertebrados marinos",
    "SNGM Mamíferos marinos", "SNGM Microfauna sin especificar",
    "SNGM Peces, esqueletos y escamas", "SNGM Polen y o esporas",
    "SNGM Radiolarios", "SNGM Raiz en posición de vida",
    "SNGM Rastros y pisadas 1", "SNGM Rastros y pisadas 2",
    "SNGM Restos de tronco", "SNGM Trazas fósiles 2",
    "SNGM Trazas fósiles 3", "SNGM Trazas fósiles",
    "SNGM Tronco en posición de vida", "SNGM Vertebrados"
];