// Registro y carga de tramas SVG
export const tramasSVG = {};

export function registrarTramaSVG(nombre, ruta) {
  if (!tramasSVG[nombre]) {
    tramasSVG[nombre] = new Image();
    tramasSVG[nombre].src = ruta;
    tramasSVG[nombre].onerror = () => console.error(`❌ Error cargando trama SVG: ${nombre} desde ${ruta}`);
    tramasSVG[nombre].onload = () => console.log(`✅ Trama SVG cargada: ${nombre}`);
  }
}

// Registrar todas las tramas
export function registrarTodasLasTramas() {
  registrarTramaSVG('conglomerado_op1', '601 Grava o conglomerado opción1.svg');
    registrarTramaSVG('conglomerado_op2', '602 Conglomerado o grava opción 2.svg');
    registrarTramaSVG('conglomerado_cruzado', '603 Grava o conglomerado con estratificación cruzada.svg');
    registrarTramaSVG('brecha_op1', '605 Brecha 1ra opción.svg');
    registrarTramaSVG('brecha_op2', '606 Brecha 2da opción.svg');
    registrarTramaSVG('arenisca_maciza', '607 Arenisca o arena maciza.svg');
    registrarTramaSVG('arenisca_estratificada', '608 Arenisca o arena estratificada.svg');
    registrarTramaSVG('arenisca_cruzada_op1', '609 Arenisca o arena con estratificación cruzada 1ra opción.svg');
    registrarTramaSVG('arenisca_cruzada_op2', '610 Arenisca o arena con estratificación cruzada 2daa opción.svg');
    registrarTramaSVG('arenisca_ondulada', '611 Arenisca o arena con estratificación ondulada.svg');
    registrarTramaSVG('arenisca_arcillosa', '612 Arenisca arcillosa o argilizada.svg');
    registrarTramaSVG('arenisca_calcare', '613 Arenisca calcárea.svg');
    registrarTramaSVG('arenisca_dolomitica', '614 Arenisca dolomítica.svg');
    registrarTramaSVG('limolita_arcillosa', '616 Limo, limolita o lutita arcillosa.svg');
    registrarTramaSVG('limolita_calcare', '617 Limolita calcárea.svg');
    registrarTramaSVG('limolita_dolomitica', '618 Limolita dolomítica.svg');
    registrarTramaSVG('lutita_arenosa', '619 Lutita arenosa o limosa.svg');
    registrarTramaSVG('lutita', '620 Arcilla o lutita.svg');
    registrarTramaSVG('lutita_chert', '621 Lutita chert o chert pizarroso.svg');
    registrarTramaSVG('lutita_dolomitica', '622 Lutita dolomítica.svg');
    registrarTramaSVG('lutita_calcare', '623 Lutita calcárea o marmol.svg');
    registrarTramaSVG('lutita_carbonosa', '624 Lutita carbonosa.svg');
    registrarTramaSVG('lutita_petrolifera', '625 Lutita petrolífera.svg');
    registrarTramaSVG('creta', '626 Creta.svg');
    registrarTramaSVG('caliza', '627 Caliza.svg');
    registrarTramaSVG('caliza_clastica', '628 Caliza clástica.svg');
    registrarTramaSVG('caliza_fosilifera', '629 Caliza fosilifera clástica.svg');
    registrarTramaSVG('caliza_nodular', '630 Caliza nodular o con estratificación irregular.svg');
    registrarTramaSVG('caliza_madrigueras', '631 Caliza, rellenos irregulares -madrigueras- de dolomita sacaroidal.svg');
    registrarTramaSVG('caliza_cruzada', '632 Caliza con estratificación cruzada.svg');
    registrarTramaSVG('caliza_chert_cruzada', '633 Caliza chert con estratificación cruzada.svg');
    registrarTramaSVG('caliza_arenosa_chert', '634 Caliza arenosa y con chert, clástica con estratificación cruzada.svg');
    registrarTramaSVG('caliza_oolitica', '635 Caliza oolitica.svg');
    registrarTramaSVG('caliza_arenosa', '636 Caliza arenosa.svg');
    registrarTramaSVG('caliza_limosa', '637 Caliza limosa.svg');
    registrarTramaSVG('caliza_lutitica', '638 Caliza lutítica o arcillosa.svg');
    registrarTramaSVG('caliza_chert_op1', '639 Caliza con chert 1ra opción.svg');
    registrarTramaSVG('caliza_chert_op2', '640 Caliza con chert 2da opción.svg');
    registrarTramaSVG('caliza_dolomitica', '641 Caliza dolomítica, dolomita calcárea, dolomía calcárea.svg');
    registrarTramaSVG('dolomita', '642 Dolomita o dolomía.svg');
    registrarTramaSVG('dolomita_cruzada', '643 Dolomita o dolomía con estratificación cruzada.svg');
    registrarTramaSVG('dolomita_oolitica', '644 Dolomita o dolomía oolítica.svg');
    registrarTramaSVG('dolomita_arenosa', '645 Dolomita o dolomía arenosa.svg');
    registrarTramaSVG('dolomita_limosa', '646 Dolomita o dolomía limosa.svg');
    registrarTramaSVG('dolomita_lutitica', '647 Dolomita o dolomía arcillosa o lutítica.svg');
    registrarTramaSVG('dolomita_chert', '648 Dolomita o dolomía con chert.svg');
    registrarTramaSVG('chert_op1', '649 Chert estratificado 1ra opción.svg');
    registrarTramaSVG('chert_op2', '650 Chert estratificado 2da opción.svg');
    registrarTramaSVG('chert_fosilifero', '651 Chert estratificado fosilifero.svg');
    registrarTramaSVG('roca_fosilifera', '652 Roca fosilífera.svg');
    registrarTramaSVG('roca_diatomitica', '653 Roca diatomítica o con diatomeas.svg');
    registrarTramaSVG('subgrauvaca', '654 Subgrauvaca.svg');
    registrarTramaSVG('subgrauvaca_cruzada', '655 Subgrauvaca con estratificación cruzada.svg');
    registrarTramaSVG('subgrauvaca_ondulada', '656 Subgrauvaca con estratificación ondulada.svg');
    registrarTramaSVG('turba', '657 Turba.svg');
    registrarTramaSVG('carbon', '658 Carbón.svg');
    registrarTramaSVG('carbon_impuro', '659 Carbón con huesos o carbón impuro.svg');
    registrarTramaSVG('paleosuelo', '660 Paleosuelo, arcilla basal, underclay.svg');
    registrarTramaSVG('flintclay', '661 Flintclay o pedernal.svg');
    registrarTramaSVG('bentonita', '662 Bentonita.svg');
    registrarTramaSVG('glauconita', '663 Glauconita.svg');
    registrarTramaSVG('limonita', '664 Limonita.svg');
    registrarTramaSVG('siderita', '665 Siderita.svg');
    registrarTramaSVG('fosforita', '666 Roca fosfática nodular, fósforita.svg');
    registrarTramaSVG('yeso', '667 Yeso.svg');
    registrarTramaSVG('sal', '668 Sal.svg');
    registrarTramaSVG('arenisca_limolita', '669 Arenisca y limolta interestratificada.svg');
    registrarTramaSVG('arenisca_lutita', '670 Arenisca y lutita interestratificada.svg');
    registrarTramaSVG('arenisca_lutita_ondulada', '671 Arenisca y lutita interestratificada con estratificación ondulada.svg');
    registrarTramaSVG('lutita_caliza_limosa', '672 Lutita y caliza limosa interestratificada.svg');
    registrarTramaSVG('lutita_caliza_op1', '673 Lutita y caliza interestratificada 1ra opción.svg');
    registrarTramaSVG('lutita_caliza_op2', '674 Lutita y caliza interestratificada 2da opción.svg');
    registrarTramaSVG('lutita_caliza_calcare', '675 Lutita calcarea y caliza interestratificada.svg');
    registrarTramaSVG('caliza_limosa_lutita_op1', '676 Caliza limosa y lutita interestatificada 1ra opción.svg');
    registrarTramaSVG('caliza_lutita_op1', '677 Caliza y lutita interestratificada 1ra opción.svg');
    registrarTramaSVG('caliza_lutita_op2', '678 Caliza y lutita interestratificada 2da opción.svg');
    registrarTramaSVG('caliza_lutita_op3', '679 Caliza y lutita interestratificada 3ra opción.svg');
    registrarTramaSVG('caliza_lutita_calcare', '680 Caliza y lutita calcarea interestratificada.svg');
    registrarTramaSVG('till_op1', '681 Till o diamicto 1ra opción.svg');
    registrarTramaSVG('till_op2', '682 Till o diamicto 2da opción.svg');
    registrarTramaSVG('till_op3', '683 Till o diamicto 3ra opción.svg');
    registrarTramaSVG('loess_op1', '684 Loess 1ra opción.svg');
    registrarTramaSVG('loess_op2', '685 Loess 2da opción.svg');
    registrarTramaSVG('loess_op3', '686 Loess 3ra opción.svg');
    registrarTramaSVG('metamorfismo', '701 Metamorfismo.svg');
    registrarTramaSVG('cuarcita', '702 Cuarcita.svg');
    registrarTramaSVG('pizarra', '703 Pizarra.svg');
    registrarTramaSVG('granito_esquistoso', '704 Granito esquistoso o gneisico.svg');
    registrarTramaSVG('esquisto', '705 Esquisto.svg');
    registrarTramaSVG('esquisto_contorsionado', '706 Esquisto contorsionado.svg');
    registrarTramaSVG('esquisto_gneis', '707 Esquisto y gneis.svg');
    registrarTramaSVG('gneis', '708 Gneis.svg');
    registrarTramaSVG('gneis_contorsionado', '709 Gneis contorsionado.svg');
    registrarTramaSVG('esteatita', '710 Esteatita, talco o serpentinita.svg');
    registrarTramaSVG('roca_tufitica', '711 Roca tufítica.svg');
    registrarTramaSVG('toba_cristalina', '712 Toba cristalina.svg');
    registrarTramaSVG('toba_desvitrificada', '713 Toba desvitrificada.svg');
    registrarTramaSVG('brecha_volcanica_toba', '714 Brecha volcánica y toba.svg');
    registrarTramaSVG('brecha_volcanica', '715 Brecha volcánica o aglomerado.svg');
    registrarTramaSVG('roca_zeolitica', '716 Roca zeolítica.svg');
    registrarTramaSVG('flujos_basalticos', '717 Flujos basálticos.svg');
    registrarTramaSVG('granito_op1', '718 Granito 1ra opción.svg');
    registrarTramaSVG('granito_op2', '719 Granito 2da opción.svg');
    registrarTramaSVG('roca_ignea_bandeada', '720 Roca ígnea bandeada.svg');
    registrarTramaSVG('roca_ignea_op1', '721 Roca ígnea 1ra opción.svg');
    registrarTramaSVG('roca_ignea_op2', '722 Roca ígnea 2da opción.svg');
    registrarTramaSVG('roca_ignea_op3', '723 Roca ígnea 3ra opción.svg');
    registrarTramaSVG('roca_ignea_op4', '724 Roca ígnea 4ta.svg');
    registrarTramaSVG('roca_ignea_op5', '725 Roca ígnea 5ta.svg');
    registrarTramaSVG('roca_ignea_op6', '726 Roca ígnea 6ta.svg');
    registrarTramaSVG('roca_ignea_op7', '727 Roca ígnea 7ma.svg');
    registrarTramaSVG('roca_ignea_op8', '728 Roca ígnea 8va.svg');
    registrarTramaSVG('roca_porfirica_op1', '729 Roca porfírica 1ra opción.svg');
    registrarTramaSVG('roca_porfirica_op2', '730 Roca porfírica 2da opción.svg');
    registrarTramaSVG('vitrofiro', '731 Vitrófiro.svg');
    registrarTramaSVG('cuarzo', '732 Cuarzo.svg');
    registrarTramaSVG('mineralizacion', '733 Mineralización.svg');
    registrarTramaSVG('SNGM 001 Grava o conglomerado imbricado clastosoportado', 'SNGM 001 Grava o conglomerado imbricado clastosoportado.svg');
}